import type { Client, Chantier, Devis, DemandeDevis, Fournisseur, Materiau, Prestation, SousTraitant, User } from '@/types';

export const demoClients: Client[] = [
  {
    id: 1,
    nom: 'Dupont',
    prenom: 'Jean',
    email: 'jean.dupont@email.com',
    telephone: '06 12 34 56 78',
    adresse: '123 Rue de Paris',
    ville: 'Paris',
    codePostal: '75001',
    statut: 'ACTIF',
    dateCreation: '2024-01-15',
  },
  {
    id: 2,
    nom: 'Martin',
    prenom: 'Marie',
    email: 'marie.martin@email.com',
    telephone: '06 98 76 54 32',
    adresse: '45 Avenue des Champs',
    ville: 'Lyon',
    codePostal: '69001',
    statut: 'ACTIF',
    dateCreation: '2024-02-20',
  },
  {
    id: 3,
    nom: 'Bernard',
    prenom: 'Pierre',
    email: 'pierre.bernard@email.com',
    telephone: '06 11 22 33 44',
    adresse: '78 Boulevard Haussmann',
    ville: 'Marseille',
    codePostal: '13001',
    statut: 'ACTIF',
    dateCreation: '2024-03-10',
  },
];

export const demoChantiers: Chantier[] = [
  {
    id: 1,
    reference: 'CH-2024-001',
    clientId: 1,
    clientNom: 'Dupont Jean',
    adresse: '123 Rue de Paris, Paris',
    statut: 'EN_COURS',
    dateDebut: '2024-04-01',
    dateFin: '2024-06-30',
    budget: 45000,
    description: 'Rénovation complète salle de bain',
  },
  {
    id: 2,
    reference: 'CH-2024-002',
    clientId: 2,
    clientNom: 'Martin Marie',
    adresse: '45 Avenue des Champs, Lyon',
    statut: 'PLANIFIE',
    dateDebut: '2024-07-01',
    dateFin: '2024-09-30',
    budget: 75000,
    description: 'Extension maison avec terrasse',
  },
  {
    id: 3,
    reference: 'CH-2024-003',
    clientId: 3,
    clientNom: 'Bernard Pierre',
    adresse: '78 Boulevard Haussmann, Marseille',
    statut: 'TERMINE',
    dateDebut: '2024-01-15',
    dateFin: '2024-03-15',
    budget: 32000,
    description: 'Installation chauffage central',
  },
];

export const demoDevis: Devis[] = [
  {
    id: 1,
    reference: 'DEV-2024-001',
    clientId: 1,
    clientNom: 'Dupont Jean',
    chantierId: 1,
    statut: 'VALIDE',
    dateCreation: '2024-03-15',
    dateValidation: '2024-03-20',
    montantHT: 42000,
    montantTTC: 50400,
    tva: 20,
    lignes: [],
  },
  {
    id: 2,
    reference: 'DEV-2024-002',
    clientId: 2,
    clientNom: 'Martin Marie',
    chantierId: 2,
    statut: 'ENVOYE',
    dateCreation: '2024-05-10',
    montantHT: 68000,
    montantTTC: 81600,
    tva: 20,
    lignes: [],
  },
  {
    id: 3,
    reference: 'DEV-2024-003',
    clientId: 3,
    clientNom: 'Bernard Pierre',
    chantierId: 3,
    statut: 'EN_PREPARATION',
    dateCreation: '2024-06-01',
    montantHT: 0,
    montantTTC: 0,
    tva: 20,
    lignes: [],
  },
];

export const demoDemandesDevis: DemandeDevis[] = [
  {
    id: 1,
    reference: 'DD-2024-001',
    clientId: 1,
    clientNom: 'Dupont Jean',
    statut: 'TRAITE',
    dateCreation: '2024-03-10',
    description: 'Rénovation salle de bain',
    priorite: 'HAUTE',
  },
  {
    id: 2,
    reference: 'DD-2024-002',
    clientId: 2,
    clientNom: 'Martin Marie',
    statut: 'EN_COURS',
    dateCreation: '2024-05-05',
    description: 'Extension maison',
    priorite: 'MOYENNE',
  },
  {
    id: 3,
    reference: 'DD-2024-003',
    clientId: 3,
    clientNom: 'Bernard Pierre',
    statut: 'NOUVEAU',
    dateCreation: '2024-06-15',
    description: 'Installation climatisation',
    priorite: 'BASSE',
  },
];

export const demoFournisseurs: Fournisseur[] = [
  {
    id: 1,
    nom: 'BricoPro',
    email: 'contact@bricopro.fr',
    telephone: '01 23 45 67 89',
    adresse: '10 Zone Industrielle',
    ville: 'Paris',
    codePostal: '75012',
    statut: 'ACTIF',
    specialite: 'Matériaux construction',
  },
  {
    id: 2,
    nom: 'Plomberie Express',
    email: 'info@plomberie-express.fr',
    telephone: '02 34 56 78 90',
    adresse: '25 Rue du Commerce',
    ville: 'Lyon',
    codePostal: '69002',
    statut: 'ACTIF',
    specialite: 'Plomberie',
  },
  {
    id: 3,
    nom: 'Électricité Plus',
    email: 'contact@electricite-plus.fr',
    telephone: '03 45 67 89 01',
    adresse: '50 Avenue Voltaire',
    ville: 'Marseille',
    codePostal: '13003',
    statut: 'ACTIF',
    specialite: 'Électricité',
  },
];

export const demoMateriaux: Materiau[] = [
  {
    id: 1,
    nom: 'Carrelage grès cérame',
    categorie: 'Revêtement sol',
    unite: 'M2',
    prixAchat: 25,
    prixVente: 35,
    stock: 500,
    fournisseurId: 1,
    fournisseurNom: 'BricoPro',
  },
  {
    id: 2,
    nom: 'Peinture acrylique blanc',
    categorie: 'Peinture',
    unite: 'L',
    prixAchat: 18,
    prixVente: 28,
    stock: 200,
    fournisseurId: 1,
    fournisseurNom: 'BricoPro',
  },
  {
    id: 3,
    nom: 'Robinet cuisine chromé',
    categorie: 'Plomberie',
    unite: 'UNITE',
    prixAchat: 45,
    prixVente: 65,
    stock: 50,
    fournisseurId: 2,
    fournisseurNom: 'Plomberie Express',
  },
];

export const demoPrestations: Prestation[] = [
  {
    id: 1,
    nom: 'Installation carrelage',
    categorie: 'Revêtement',
    unite: 'M2',
    prixUnitaire: 45,
    mainOeuvre: 30,
    materiauId: 1,
    materiauNom: 'Carrelage grès cérame',
  },
  {
    id: 2,
    nom: 'Peinture mur intérieur',
    categorie: 'Peinture',
    unite: 'M2',
    prixUnitaire: 25,
    mainOeuvre: 18,
    materiauId: 2,
    materiauNom: 'Peinture acrylique blanc',
  },
  {
    id: 3,
    nom: 'Installation plomberie cuisine',
    categorie: 'Plomberie',
    unite: 'FORFAIT',
    prixUnitaire: 350,
    mainOeuvre: 250,
    materiauId: 3,
    materiauNom: 'Robinet cuisine chromé',
  },
];

export const demoSousTraitants: SousTraitant[] = [
  {
    id: 1,
    nom: 'Maçonnerie Durand',
    email: 'contact@maconnerie-durand.fr',
    telephone: '04 56 78 90 12',
    adresse: '15 Zone Artisanale',
    ville: 'Paris',
    codePostal: '75015',
    statut: 'ACTIF',
    specialite: 'Maçonnerie',
    siret: '12345678900012',
  },
  {
    id: 2,
    nom: 'Électricite Services',
    email: 'info@electricite-services.fr',
    telephone: '05 67 89 01 23',
    adresse: '30 Rue des Artisans',
    ville: 'Lyon',
    codePostal: '69003',
    statut: 'ACTIF',
    specialite: 'Électricité',
    siret: '23456789000023',
  },
  {
    id: 3,
    nom: 'Plomberie Pro',
    email: 'contact@plomberie-pro.fr',
    telephone: '06 78 90 12 34',
    adresse: '45 Avenue Industrie',
    ville: 'Marseille',
    codePostal: '13004',
    statut: 'ACTIF',
    specialite: 'Plomberie',
    siret: '34567890100034',
  },
];

export const demoUsers: User[] = [
  {
    id: 1,
    nom: 'Admin',
    prenom: 'Système',
    email: 'admin@baticrm.fr',
    role: 'ADMIN',
    statut: 'ACTIF',
  },
  {
    id: 2,
    nom: 'Assistante',
    prenom: 'Marie',
    email: 'marie@baticrm.fr',
    role: 'ASSISTANTE',
    statut: 'ACTIF',
  },
  {
    id: 3,
    nom: 'Technico',
    prenom: 'Pierre',
    email: 'pierre@baticrm.fr',
    role: 'TECHNICO',
    statut: 'ACTIF',
  },
  {
    id: 4,
    nom: 'Chef',
    prenom: 'Jean',
    email: 'jean@baticrm.fr',
    role: 'CHEF_CHANTIER',
    statut: 'ACTIF',
  },
  {
    id: 5,
    nom: 'Fournisseur',
    prenom: 'Paul',
    email: 'paul@baticrm.fr',
    role: 'FOURNISSEUR',
    statut: 'ACTIF',
  },
];

export const demoData = {
  clients: demoClients,
  chantiers: demoChantiers,
  devis: demoDevis,
  demandesDevis: demoDemandesDevis,
  fournisseurs: demoFournisseurs,
  materiaux: demoMateriaux,
  prestations: demoPrestations,
  sousTraitants: demoSousTraitants,
  users: demoUsers,
};

export const getPaginatedDemoData = <T,>(data: T[], page: number = 1, limit: number = 10) => {
  const startIndex = (page - 1) * limit;
  const endIndex = startIndex + limit;
  const paginatedData = data.slice(startIndex, endIndex);
  
  return {
    data: paginatedData,
    meta: {
      total: data.length,
      page,
      limit,
      totalPages: Math.ceil(data.length / limit),
    },
  };
};
